export const FOOTBALL_DATA_PROVIDER = Symbol('FOOTBALL_DATA_PROVIDER');
export const NARRATIVE_GENERATOR = Symbol('NARRATIVE_GENERATOR');
export const EMBEDDING_GENERATOR = Symbol('EMBEDDING_GENERATOR');
