/*
 * Los países en español, para todo Athena.
 *
 * El proveedor los entrega en inglés —y a las selecciones las nombra igual que al país: "Spain",
 * "South Africa"—, así que sin esto un cuadro del Mundial en un producto en castellano queda lleno
 * de nombres ingleses. Vive en el dominio y no en la web porque el API también lo necesita: las
 * selecciones se guardan ya traducidas, y de ahí sale su slug.
 *
 * La clave se normaliza —minúsculas, sin guiones ni puntos— porque el mismo país llega de tres
 * formas según el endpoint: "South Africa" en un equipo, "South-Africa" en un país, "Rep. Of
 * Ireland" en una selección. Lo que no está en la lista se devuelve tal cual: mejor el nombre del
 * proveedor que un hueco.
 */
const NOMBRE: Record<string, string> = {
  'afghanistan': 'Afganistán',
  'albania': 'Albania',
  'algeria': 'Argelia',
  'american samoa': 'Samoa Americana',
  'andorra': 'Andorra',
  'angola': 'Angola',
  'anguilla': 'Anguila',
  'antigua and barbuda': 'Antigua y Barbuda',
  'argentina': 'Argentina',
  'armenia': 'Armenia',
  'aruba': 'Aruba',
  'australia': 'Australia',
  'austria': 'Austria',
  'azerbaijan': 'Azerbaiyán',
  'bahamas': 'Bahamas',
  'bahrain': 'Baréin',
  'bangladesh': 'Bangladés',
  'barbados': 'Barbados',
  'belarus': 'Bielorrusia',
  'belgium': 'Bélgica',
  'belize': 'Belice',
  'benin': 'Benín',
  'bermuda': 'Bermudas',
  'bhutan': 'Bután',
  'bolivia': 'Bolivia',
  'bonaire': 'Bonaire',
  'bosnia & herzegovina': 'Bosnia y Herzegovina',
  'botswana': 'Botsuana',
  'brazil': 'Brasil',
  'british virgin islands': 'Islas Vírgenes Británicas',
  'brunei': 'Brunéi',
  'bulgaria': 'Bulgaria',
  'burkina faso': 'Burkina Faso',
  'burundi': 'Burundi',
  'cambodia': 'Camboya',
  'cameroon': 'Camerún',
  'canada': 'Canadá',
  'cape verde islands': 'Cabo Verde',
  'cayman islands': 'Islas Caimán',
  'central african republic': 'República Centroafricana',
  'chad': 'Chad',
  'chile': 'Chile',
  'china': 'China',
  'chinese taipei': 'Taipéi Chino',
  'colombia': 'Colombia',
  'comoros': 'Comoras',
  'congo': 'Congo',
  'congo dr': 'RD Congo',
  'cook islands': 'Islas Cook',
  'costa rica': 'Costa Rica',
  'croatia': 'Croacia',
  'cuba': 'Cuba',
  'curaçao': 'Curazao',
  'cyprus': 'Chipre',
  'czechia': 'Chequia',
  'czech republic': 'Chequia',
  'denmark': 'Dinamarca',
  'djibouti': 'Yibuti',
  'dominica': 'Dominica',
  'dominican republic': 'República Dominicana',
  'ecuador': 'Ecuador',
  'egypt': 'Egipto',
  'el salvador': 'El Salvador',
  'england': 'Inglaterra',
  'equatorial guinea': 'Guinea Ecuatorial',
  'eritrea': 'Eritrea',
  'estonia': 'Estonia',
  'eswatini': 'Esuatini',
  'ethiopia': 'Etiopía',
  'faroe islands': 'Islas Feroe',
  'fiji': 'Fiyi',
  'finland': 'Finlandia',
  'france': 'Francia',
  'french guyana': 'Guayana Francesa',
  'fyr macedonia': 'Macedonia del Norte',
  'north macedonia': 'Macedonia del Norte',
  'gabon': 'Gabón',
  'gambia': 'Gambia',
  'georgia': 'Georgia',
  'germany': 'Alemania',
  'ghana': 'Ghana',
  'gibraltar': 'Gibraltar',
  'greece': 'Grecia',
  'grenada': 'Granada',
  'guam': 'Guam',
  'guatemala': 'Guatemala',
  'guinea': 'Guinea',
  'guinea bissau': 'Guinea-Bisáu',
  'guyana': 'Guyana',
  'haiti': 'Haití',
  'honduras': 'Honduras',
  'hong kong': 'Hong Kong',
  'hungary': 'Hungría',
  'iceland': 'Islandia',
  'india': 'India',
  'indonesia': 'Indonesia',
  'iran': 'Irán',
  'iraq': 'Irak',
  'ireland': 'Irlanda',
  'rep of ireland': 'Irlanda',
  'israel': 'Israel',
  'italy': 'Italia',
  'ivory coast': 'Costa de Marfil',
  "cote d'ivoire": 'Costa de Marfil',
  'jamaica': 'Jamaica',
  'japan': 'Japón',
  'jordan': 'Jordania',
  'kazakhstan': 'Kazajistán',
  'kenya': 'Kenia',
  'kosovo': 'Kosovo',
  'kuwait': 'Kuwait',
  'kyrgyzstan': 'Kirguistán',
  'laos': 'Laos',
  'latvia': 'Letonia',
  'lebanon': 'Líbano',
  'lesotho': 'Lesoto',
  'liberia': 'Liberia',
  'libya': 'Libia',
  'liechtenstein': 'Liechtenstein',
  'lithuania': 'Lituania',
  'luxembourg': 'Luxemburgo',
  'madagascar': 'Madagascar',
  'malawi': 'Malaui',
  'malaysia': 'Malasia',
  'maldives': 'Maldivas',
  'mali': 'Malí',
  'malta': 'Malta',
  'martinique': 'Martinica',
  'mauritania': 'Mauritania',
  'mauritius': 'Mauricio',
  'mexico': 'México',
  'moldova': 'Moldavia',
  'mongolia': 'Mongolia',
  'montenegro': 'Montenegro',
  'morocco': 'Marruecos',
  'mozambique': 'Mozambique',
  'myanmar': 'Birmania',
  'namibia': 'Namibia',
  'nepal': 'Nepal',
  'netherlands': 'Países Bajos',
  'new caledonia': 'Nueva Caledonia',
  'new zealand': 'Nueva Zelanda',
  'nicaragua': 'Nicaragua',
  'niger': 'Níger',
  'nigeria': 'Nigeria',
  'north korea': 'Corea del Norte',
  'northern ireland': 'Irlanda del Norte',
  'norway': 'Noruega',
  'oman': 'Omán',
  'pakistan': 'Pakistán',
  'palestine': 'Palestina',
  'panama': 'Panamá',
  'papua new guinea': 'Papúa Nueva Guinea',
  'paraguay': 'Paraguay',
  'peru': 'Perú',
  'philippines': 'Filipinas',
  'poland': 'Polonia',
  'portugal': 'Portugal',
  'puerto rico': 'Puerto Rico',
  'qatar': 'Catar',
  'romania': 'Rumanía',
  'russia': 'Rusia',
  'rwanda': 'Ruanda',
  'saint martin': 'San Martín',
  'samoa': 'Samoa',
  'san marino': 'San Marino',
  'saudi arabia': 'Arabia Saudita',
  'scotland': 'Escocia',
  'senegal': 'Senegal',
  'serbia': 'Serbia',
  'seychelles': 'Seychelles',
  'sierra leone': 'Sierra Leona',
  'singapore': 'Singapur',
  'sint maarten': 'Sint Maarten',
  'slovakia': 'Eslovaquia',
  'slovenia': 'Eslovenia',
  'solomon islands': 'Islas Salomón',
  'somalia': 'Somalia',
  'south africa': 'Sudáfrica',
  'south korea': 'Corea del Sur',
  'south sudan': 'Sudán del Sur',
  'spain': 'España',
  'sri lanka': 'Sri Lanka',
  'st kitts and nevis': 'San Cristóbal y Nieves',
  'st lucia': 'Santa Lucía',
  'st vincent / grenadines': 'San Vicente y las Granadinas',
  'sudan': 'Sudán',
  'suriname': 'Surinam',
  'sweden': 'Suecia',
  'switzerland': 'Suiza',
  'syria': 'Siria',
  'tahiti': 'Tahití',
  'tajikistan': 'Tayikistán',
  'tanzania': 'Tanzania',
  'thailand': 'Tailandia',
  'timor leste': 'Timor Oriental',
  'togo': 'Togo',
  'tonga': 'Tonga',
  'trinidad and tobago': 'Trinidad y Tobago',
  'tunisia': 'Túnez',
  'türkiye': 'Turquía',
  'turkey': 'Turquía',
  'turkmenistan': 'Turkmenistán',
  'turks and caicos islands': 'Islas Turcas y Caicos',
  'uganda': 'Uganda',
  'ukraine': 'Ucrania',
  'united arab emirates': 'Emiratos Árabes Unidos',
  'united states': 'Estados Unidos',
  'usa': 'Estados Unidos',
  'uruguay': 'Uruguay',
  'us virgin islands': 'Islas Vírgenes de EE. UU.',
  'uzbekistan': 'Uzbekistán',
  'vanuatu': 'Vanuatu',
  'venezuela': 'Venezuela',
  'vietnam': 'Vietnam',
  'wales': 'Gales',
  'world': 'Internacional',
  /*
   * Las confederaciones no son países, pero el proveedor las manda en el mismo campo: un título
   * continental llega con "Europe" o "South America" donde otro trae "España". Sin esto, un
   * palmarés en español se llena de nombres en inglés.
   */
  'europe': 'Europa',
  'south america': 'Sudamérica',
  'north america': 'Norteamérica',
  'n/c america': 'Norteamérica',
  'africa': 'África',
  'asia': 'Asia',
  'oceania': 'Oceanía',
  'yemen': 'Yemen',
  'zambia': 'Zambia',
  'zimbabwe': 'Zimbabue',
};

const clave = (nombre: string): string =>
  nombre
    .toLowerCase()
    .replace(/[-–]/g, ' ')
    .replace(/\./g, '')
    .replace(/\s+/g, ' ')
    .trim();

export function paisEnEspanol(pais: string | null | undefined): string | null {
  if (!pais) return null;
  return NOMBRE[clave(pais)] ?? pais;
}
