/**
 * Eventos de fútbol: lo que pasa en la cancha y en el vestuario alrededor de ella.
 *
 * Cada opción cambia algo medible. Ninguna es "la correcta": entrenar de más sube el físico y baja la
 * frescura, pedirle la titularidad al técnico puede ganarte el puesto o el banco. Si una opción fuera
 * siempre mejor, dejaría de ser una decisión.
 */
import type { Evento } from './motor.js';

export const EVENTOS_DE_FUTBOL: Evento[] = [
  {
    id: 'futbol-primer-entrenamiento',
    categoria: 'futbol',
    rareza: 'comun',
    titulo: 'La primera práctica con los grandes',
    texto:
      'Te suben a entrenar con el plantel profesional de {club}. En el primer rondo te toca al lado de los referentes y todos miran cómo te mueves.',
    tipoDeRecuerdo: 'decision',
    condiciones: { edadMax: 20, temporadasMin: 0 },
    cooldown: 0,
    peso: 2.5,
    opciones: [
      {
        id: 'mostrarse',
        texto: 'Pedir la pelota y jugar como sabes',
        pista: 'Alto riesgo, alta recompensa: si sale bien, el técnico te ve.',
        efectos: {
          vida: { confianza: 8, estres: 4 },
          relaciones: { dt: { confianza: 6 }, companeros: { respeto: 4 } },
          etiquetas: ['personalidad:atrevido'],
          balance: 6,
        },
        resultado:
          'Pediste la pelota siempre. Perdiste tres, ganaste diez, y el técnico se quedó mirándote más de lo normal.',
      },
      {
        id: 'perfil-bajo',
        texto: 'Pasarla simple y escuchar',
        pista: 'Nadie se quema el primer día. Tampoco nadie te descubre.',
        efectos: {
          vida: { estres: -4 },
          relaciones: { companeros: { confianza: 5 } },
          personalidad: { disciplina: 2 },
          etiquetas: ['personalidad:prudente'],
          balance: 2,
        },
        resultado: 'Tocaste corto, sin sobresaltos. Los veteranos te bancaron y el técnico apenas te registró.',
      },
      {
        id: 'mirar',
        texto: 'Mirar y aprender antes de pedir la pelota',
        pista: 'Nadie se molesta. Nadie se acuerda tampoco.',
        efectos: {
          personalidad: { profesionalismo: 5, ego: -3 },
          relaciones: { companeros: { confianza: 4 } },
          balance: 2,
        },
        resultado: 'Tocaste ocho pelotas en dos horas y te fuiste sabiendo cómo se movían todos.',
      },
      {
        id: 'marcar-al-crack',
        texto: 'Ir a marcar al mejor del plantel',
        pista: 'O te respetan desde el primer día, o te ganás un problema.',
        efectos: {
          personalidad: { ambicion: 6, temperamento: 5 },
          etiquetas: ['futbol:atrevido'],
        },
        riesgo: {
          prob: 0.55,
          bien: {
            relaciones: { companeros: { respeto: 14 }, dt: { confianza: 8 } },
            balance: 5,
          },
          mal: {
            relaciones: { companeros: { rencor: 12 } },
            vida: { confianza: -8 },
            balance: -4,
          },
          relatoBien: 'Le ganaste dos y te aplaudieron. Desde ese día te pasaban la pelota.',
          relatoMal: 'Te hizo un caño delante de todos y el vestuario se rió una semana.',
        },
        resultado: 'Te fuiste derecho a marcar al que llevaba la diez.',
      },
    ],
  },
  {
    id: 'futbol-doble-turno',
    categoria: 'futbol',
    rareza: 'comun',
    titulo: 'Doble turno',
    texto: 'El preparador físico te ofrece quedarte a un segundo turno tres veces por semana.',
    tipoDeRecuerdo: 'decision',
    cooldown: 6,
    opciones: [
      {
        id: 'aceptar',
        texto: 'Quedarte a entrenar',
        pista: 'El físico sube. El cuerpo lo paga.',
        efectos: {
          atributos: { fisico: 3, ritmo: 1 },
          vida: { condicion: -6, felicidad: -3 },
          personalidad: { profesionalismo: 3 },
          balance: 4,
        },
        resultado: 'Te quedaste. En dos meses te notaron el cambio en los duelos.',
      },
      {
        id: 'descansar',
        texto: 'Priorizar el descanso',
        pista: 'Llegas fresco al fin de semana.',
        efectos: { vida: { condicion: 7, felicidad: 3 }, balance: 1 },
        resultado: 'Elegiste llegar entero al domingo. El cuerpo te lo agradeció.',
      },
      {
        id: 'tecnica',
        texto: 'Cambiarlo por trabajo de pelota',
        pista: 'Menos músculo, más pie.',
        efectos: {
          atributos: { regate: 2, tiro: 2 },
          vida: { condicion: -2 },
          balance: 3,
        },
        resultado: 'Te quedaste, pero pateando. Mil tiros al arco vacío antes de irte.',
      },
      {
        id: 'gimnasio-propio',
        texto: 'Pagarte un preparador aparte',
        pista: 'Cuesta dinero y nadie del club se entera.',
        efectos: {
          vida: { dinero: -0.3, condicion: 8, forma: 6 },
          atributos: { fisico: 2 },
          personalidad: { profesionalismo: 7 },
          etiquetas: ['futbol:obsesivo'],
          balance: 5,
        },
        resultado: 'Contrataste a alguien que te entrenaba a las siete de la mañana. Nadie lo supo.',
      },
    ],
  },
  {
    id: 'futbol-pedir-titularidad',
    categoria: 'futbol',
    rareza: 'infrecuente',
    titulo: 'Hablar con el técnico',
    texto:
      '{dt} te dejó afuera del once tres partidos seguidos. Tienes la puerta de su oficina a diez metros.',
    tipoDeRecuerdo: 'conflicto',
    condiciones: { roles: ['suplente', 'rotacion', 'promesa'], temporadasMin: 1 },
    cooldown: 4,
    peso: 1.6,
    opciones: [
      {
        id: 'encarar',
        texto: 'Entrar y pedir explicaciones',
        pista: 'Puede respetarte más. O puede cerrarte la puerta.',
        efectos: {
          relaciones: { dt: { respeto: 8, rencor: 10 } },
          vida: { confianza: 5, estres: 8 },
          etiquetas: ['conflicto:dt'],
          balance: 0,
        },
        resultado:
          'Le dijiste todo lo que pensabas. Te escuchó con los brazos cruzados y te contestó dos palabras: "entrena mejor".',
      },
      {
        id: 'trabajar',
        texto: 'Callarte y romperla en los entrenamientos',
        pista: 'El camino largo.',
        efectos: {
          relaciones: { dt: { confianza: 7 }, companeros: { respeto: 3 } },
          atributos: { fisico: 1 },
          personalidad: { profesionalismo: 4 },
          balance: 5,
        },
        resultado: 'No dijiste nada. Fuiste el primero en llegar durante un mes y el técnico lo notó.',
      },
      {
        id: 'representante',
        texto: 'Que lo maneje tu representante',
        pista: 'Te sacas el problema de encima. La prensa se enterará.',
        efectos: {
          relaciones: { representante: { confianza: 6 }, dt: { rencor: 6 }, prensa: { confianza: 4 } },
          vida: { exposicion: 8 },
          titular: { texto: 'EL ENTORNO DE {APELLIDO} PRESIONA POR MINUTOS', tono: 'duda' },
          balance: -2,
        },
        resultado: 'Tu representante habló con el club. Al día siguiente estaba en todos los portales.',
      },
      {
        id: 'pedir-salida',
        texto: 'Pedirle que te deje salir a préstamo',
        pista: 'Vas a jugar. Lejos.',
        efectos: {
          relaciones: { dt: { respeto: 8 }, club: { confianza: -6 } },
          personalidad: { ambicion: 6 },
          etiquetas: ['futbol:quiere-jugar'],
          balance: 3,
        },
        resultado: 'Le dijiste que preferías jugar en otro lado antes que entrenar en este. Te entendió.',
      },
    ],
  },
  {
    id: 'futbol-clasico',
    categoria: 'futbol',
    rareza: 'comun',
    titulo: 'Semana de clásico',
    texto: 'Se viene {rival}. La ciudad no habla de otra cosa y a ti te preguntan en cada semáforo.',
    tipoDeRecuerdo: 'decision',
    condiciones: { temporadasMin: 1 },
    cooldown: 4,
    peso: 1.8,
    opciones: [
      {
        id: 'prometer',
        texto: 'Prometer que lo van a ganar',
        pista: 'La hinchada te va a amar. Si pierden, te lo van a recordar.',
        efectos: {
          vida: { carinoDeLaHinchada: 10, exposicion: 10, estres: 8 },
          relaciones: { hinchada: { confianza: 10 } },
          etiquetas: ['declaracion:clasico'],
          titular: { texto: '"VAMOS A GANAR": LA PROMESA DE {APELLIDO}', tono: 'polemica' },
          balance: 2,
        },
        resultado: 'Dijiste que iban a ganar. La frase quedó en la portada de todos los diarios.',
      },
      {
        id: 'respeto',
        texto: 'Hablar con respeto del rival',
        pista: 'Nadie se enoja. Nadie se entusiasma.',
        efectos: {
          vida: { reputacion: 4 },
          relaciones: { prensa: { respeto: 3 } },
          balance: 2,
        },
        resultado: 'Elegiste el elogio medido. Los periodistas buscaron su título en otro lado.',
      },
      {
        id: 'silencio',
        texto: 'No hablar hasta después del partido',
        pista: 'Concentrado. Aburrido.',
        efectos: { vida: { estres: -5, exposicion: -4 }, personalidad: { profesionalismo: 2 }, balance: 3 },
        resultado: 'No hablaste. En el club te lo agradecieron; en la tele lo criticaron.',
      },
      {
        id: 'provocar',
        texto: 'Meterte con el rival por redes',
        pista: 'La tribuna te ama. Si perdés, no hay dónde esconderse.',
        efectos: {
          vida: { exposicion: 18, carinoDeLaHinchada: 12 },
          personalidad: { ego: 6, temperamento: 6 },
          relaciones: { prensa: { confianza: 6 } },
          etiquetas: ['prensa:provocador'],
        },
        riesgo: {
          prob: 0.5,
          bien: {
            vida: { carinoDeLaHinchada: 16, fama: 10 },
            titular: { texto: '{APELLIDO} HABLÓ Y DESPUÉS LO HIZO EN LA CANCHA', tono: 'elogio' },
            balance: 5,
          },
          mal: {
            vida: { carinoDeLaHinchada: -18, reputacion: -12 },
            relaciones: { hinchada: { rencor: 16 } },
            titular: { texto: 'HABLÓ DE MÁS: {APELLIDO} Y UN CLÁSICO PARA OLVIDAR', tono: 'polemica' },
            balance: -8,
          },
          relatoBien: 'Dijiste que iban a ganar y metiste dos. No hay mejor manera.',
          relatoMal: 'Perdieron 3-0 y tu publicación quedó de fondo en todos los programas.',
        },
        resultado: 'Publicaste algo tres días antes del partido.',
      },
    ],
  },
  {
    id: 'futbol-capitania',
    categoria: 'futbol',
    rareza: 'raro',
    titulo: 'La cinta',
    texto: 'El capitán se va del club. {dt} te llama a su oficina con la cinta sobre el escritorio.',
    tipoDeRecuerdo: 'decision',
    condiciones: { edadMin: 24, roles: ['titular', 'estrella'], temporadasMin: 2 },
    cooldown: 0,
    opciones: [
      {
        id: 'aceptar',
        texto: 'Aceptar la capitanía',
        pista: 'Más peso, más responsabilidad, más historia.',
        efectos: {
          relaciones: { dt: { confianza: 10 }, companeros: { respeto: 10 }, hinchada: { confianza: 12 } },
          vida: { reputacion: 10, estres: 10, exposicion: 6 },
          personalidad: { ambicion: 3 },
          etiquetas: ['rol:capitan'],
          titular: { texto: '{APELLIDO}, NUEVO CAPITÁN', tono: 'elogio' },
          balance: 8,
        },
        resultado: 'Te pusiste la cinta. Desde ese día, cada micrófono del país te busca a ti.',
      },
      {
        id: 'rechazar',
        texto: 'Pedir que la lleve un veterano',
        pista: 'Menos ruido. El vestuario lo va a notar.',
        efectos: {
          relaciones: { companeros: { confianza: 8 }, dt: { respeto: -4 } },
          vida: { estres: -6 },
          etiquetas: ['personalidad:prudente'],
          balance: 1,
        },
        resultado: 'Dijiste que todavía no era tu momento. Un compañero mayor te abrazó por eso.',
      },
      {
        id: 'compartir',
        texto: 'Pedir que la lleve el más veterano',
        pista: 'El vestuario lo agradece. El técnico no tanto.',
        efectos: {
          relaciones: { companeros: { respeto: 16, confianza: 10 }, dt: { confianza: -6 } },
          personalidad: { ego: -5, lealtad: 5 },
          balance: 4,
        },
        resultado: 'Dijiste que le tocaba al que llevaba diez años. El vestuario no lo olvidó.',
      },
      {
        id: 'condiciones',
        texto: 'Aceptar, pero pidiendo cambios en el plantel',
        pista: 'Vas a tener poder de verdad. Y enemigos de verdad.',
        efectos: {
          vida: { estres: 14 },
          relaciones: { club: { respeto: 10 }, companeros: { rencor: 12 } },
          personalidad: { ambicion: 8, ego: 6 },
          etiquetas: ['futbol:capitan-fuerte'],
          balance: 2,
        },
        resultado: 'Aceptaste con una lista de tres nombres que sobraban. Dos se fueron en junio.',
      },
    ],
  },
  {
    id: 'futbol-penal-decisivo',
    categoria: 'futbol',
    rareza: 'infrecuente',
    titulo: 'Un penal para ganarlo',
    texto:
      'Minuto 89 contra {rival}. Penal a favor y el pateador habitual está en el banco. La pelota te queda a los pies.',
    tipoDeRecuerdo: 'gol',
    condiciones: { temporadasMin: 1 },
    cooldown: 2,
    peso: 1.4,
    opciones: [
      {
        id: 'patear',
        texto: 'Agarrar la pelota',
        pista: 'Vas a patear tú. Se juega en el próximo momento.',
        efectos: { vida: { estres: 6 }, etiquetas: ['acepta:presion'], balance: 4 },
        resultado: 'Levantaste la pelota del suelo y caminaste hasta el punto.',
      },
      {
        id: 'ceder',
        texto: 'Dársela a otro',
        pista: 'Nadie te va a culpar. Nadie te va a recordar.',
        efectos: {
          vida: { confianza: -5, carinoDeLaHinchada: -4 },
          relaciones: { companeros: { confianza: 3 } },
          balance: -1,
        },
        resultado: 'Se la diste a un compañero y te fuiste al borde del área a mirar.',
      },
      {
        id: 'consultar',
        texto: 'Preguntarle al técnico desde la cancha',
        pista: 'Lo decide otro. Nadie te va a culpar.',
        efectos: {
          relaciones: { dt: { confianza: 8 } },
          personalidad: { profesionalismo: 4, ego: -4 },
          balance: 1,
        },
        resultado: 'Miraste al banco y el técnico señaló al otro. Lo metió, y nadie habló de vos.',
      },
      {
        id: 'cara-o-cruz',
        texto: 'Sortearlo con el otro pateador',
        pista: 'La forma más rara de decidir algo así.',
        efectos: {
          vida: { estres: 8 },
          relaciones: { companeros: { confianza: 6 } },
          personalidad: { riesgo: 5 },
          balance: 0,
        },
        resultado: 'Lo tiraron a cara o cruz en el círculo central. La cámara lo agarró y fue meme por semanas.',
      },
    ],
  },
  {
    id: 'futbol-lesion-grave',
    categoria: 'futbol',
    rareza: 'raro',
    titulo: 'La rodilla',
    texto:
      'Sentiste el crujido antes del dolor. El parte médico dice seis meses y la palabra "ligamento" aparece tres veces.',
    tipoDeRecuerdo: 'lesion',
    condiciones: { temporadasMin: 1 },
    cooldown: 12,
    opciones: [
      {
        id: 'apurar',
        texto: 'Apurar la vuelta',
        pista: 'Vuelves antes. El cuerpo puede no perdonarlo.',
        efectos: {
          vida: { condicion: -14, forma: -10, estres: 10 },
          atributos: { ritmo: -3 },
          etiquetas: ['lesion:apurada'],
          balance: -6,
        },
        resultado: 'Volviste dos meses antes de lo que decían los médicos. La rodilla te lo recordó todo el año.',
      },
      {
        id: 'respetar',
        texto: 'Respetar los tiempos',
        pista: 'Pierdes la temporada. Salvas la carrera.',
        efectos: {
          vida: { condicion: 8, felicidad: -8, forma: -14 },
          personalidad: { profesionalismo: 5 },
          etiquetas: ['lesion:cuidada'],
          balance: 5,
        },
        resultado:
          'Hiciste cada día de la recuperación como decía el protocolo. Volviste tarde, pero volviste entero.',
      },
      {
        id: 'psicologo',
        texto: 'Empezar a ver al psicólogo del club',
        pista: 'La cabeza también se recupera.',
        efectos: {
          vida: { estres: -18, felicidad: 8, confianza: 10 },
          personalidad: { profesionalismo: 6 },
          etiquetas: ['vida:cabeza'],
          balance: 5,
        },
        resultado: 'Empezaste a ir dos veces por semana. Fue lo que más te sirvió de toda la recuperación.',
      },
      {
        id: 'desaparecer',
        texto: 'Desaparecer del club hasta estar bien',
        pista: 'Nadie te ve fallar. Nadie te ve tampoco.',
        efectos: {
          vida: { estres: -8, carinoDeLaHinchada: -10 },
          relaciones: { companeros: { confianza: -12 }, club: { rencor: 8 } },
          etiquetas: ['lesion:aislado'],
          balance: -3,
        },
        resultado: 'No apareciste por el predio en cuatro meses. Cuando volviste, medio plantel era nuevo.',
      },
    ],
  },
  {
    id: 'futbol-seleccion-primera',
    categoria: 'futbol',
    rareza: 'infrecuente',
    titulo: 'Te llaman de la selección',
    texto: 'Suena el teléfono con un número que no conoces. Es el cuerpo técnico de {pais}.',
    tipoDeRecuerdo: 'premio',
    condiciones: { ovrMin: 70, temporadasMin: 1, sinEtiquetas: ['seleccion:debut'] },
    cooldown: 0,
    peso: 2,
    opciones: [
      {
        id: 'aceptar',
        texto: 'Ir sin dudarlo',
        efectos: {
          vida: { fama: 12, reputacion: 8, felicidad: 12, exposicion: 10 },
          etiquetas: ['seleccion:debut'],
          titular: { texto: '{APELLIDO}, CONVOCADO POR PRIMERA VEZ', tono: 'elogio' },
          balance: 9,
        },
        resultado: 'Colgaste el teléfono y te quedaste mirando la pared diez minutos.',
      },
      {
        id: 'nervioso',
        texto: 'Pedir unos días para pensarlo',
        pista: 'Nadie pide unos días para esto.',
        efectos: {
          vida: { estres: 10, confianza: -6 },
          relaciones: { dt: { confianza: -8 } },
          etiquetas: ['seleccion:debut'],
          balance: -2,
        },
        resultado: 'Pediste dos días. Te llamaron igual, pero les quedó la cara que pusiste.',
      },
      {
        id: 'familia',
        texto: 'Ir y llevarte a toda tu familia',
        pista: 'Cuesta un dineral. Se acuerdan toda la vida.',
        efectos: {
          vida: { dinero: -0.3, felicidad: 22, fama: 6 },
          personalidad: { lealtad: 6 },
          etiquetas: ['seleccion:debut', 'vida:familia'],
          balance: 6,
        },
        resultado: 'Pagaste catorce pasajes. Tu abuela vio el himno desde la tribuna y no paró de llorar.',
      },
      {
        id: 'callado',
        texto: 'Ir sin decírselo a nadie',
        pista: 'Ni una publicación. Solo vos y la camiseta.',
        efectos: {
          vida: { confianza: 8, exposicion: -6 },
          personalidad: { profesionalismo: 5 },
          etiquetas: ['seleccion:debut', 'social:reservado'],
          balance: 3,
        },
        resultado: 'No lo publicaste en ningún lado. Tu vieja se enteró viendo la lista en la tele.',
      },
    ],
  },
  {
    id: 'futbol-descenso',
    categoria: 'futbol',
    rareza: 'raro',
    titulo: 'Pelear el descenso',
    texto:
      '{club} está a tres puntos de la zona roja y faltan cinco fechas. En el vestuario ya nadie habla de la copa.',
    tipoDeRecuerdo: 'decision',
    condiciones: { clubFuerzaMax: 62, temporadasMin: 1 },
    cooldown: 6,
    opciones: [
      {
        id: 'liderar',
        texto: 'Hacerte cargo del equipo',
        pista: 'Si se salvan, eres ídolo. Si se van, eres parte.',
        efectos: {
          vida: { estres: 14, carinoDeLaHinchada: 12, reputacion: 6 },
          relaciones: { companeros: { respeto: 8 }, hinchada: { confianza: 10 } },
          etiquetas: ['lider:crisis'],
          balance: 6,
        },
        resultado: 'Hablaste en el vestuario y te pusiste el equipo al hombro los últimos cinco partidos.',
      },
      {
        id: 'salvarse',
        texto: 'Cuidar tu carrera y mirar el mercado',
        pista: 'La hinchada tiene memoria.',
        efectos: {
          vida: { carinoDeLaHinchada: -14, estres: -6 },
          relaciones: { hinchada: { rencor: 12 } },
          etiquetas: ['polemica:desapego'],
          titular: { texto: '¿SE VA {APELLIDO} EN EL PEOR MOMENTO?', tono: 'polemica' },
          balance: -4,
        },
        resultado: 'Empezaste a atender llamados de representantes mientras el equipo se hundía.',
      },
      {
        id: 'quedarse',
        texto: 'Quedarte a pelear el ascenso',
        pista: 'Un año perdido en la tabla. Ganado en otra cosa.',
        efectos: {
          vida: { carinoDeLaHinchada: 26, fama: -8 },
          relaciones: { hinchada: { confianza: 24, respeto: 20 } },
          personalidad: { lealtad: 10 },
          etiquetas: ['leyenda:hinchada'],
          titular: { texto: '{APELLIDO} SE QUEDA: "ESTO LO ARREGLO YO"', tono: 'elogio' },
          balance: 7,
        },
        resultado: 'Rechazaste tres ofertas y te quedaste en segunda. En la tribuna todavía se canta eso.',
      },
      {
        id: 'culpar',
        texto: 'Decir públicamente de quién fue la culpa',
        pista: 'Alguien tiene que decirlo. Te va a costar caro.',
        efectos: {
          vida: { exposicion: 20, reputacion: -8 },
          relaciones: { club: { rencor: 20 }, hinchada: { confianza: 12 } },
          personalidad: { temperamento: 8 },
          titular: { texto: '{APELLIDO} APUNTA A LA DIRIGENCIA TRAS EL DESCENSO', tono: 'polemica' },
          etiquetas: ['conflicto:dirigencia'],
          balance: -1,
        },
        resultado: 'Dijiste que hacía tres años que no se armaba un equipo. Te rescindieron en junio.',
      },
    ],
  },
  {
    id: 'futbol-golazo',
    categoria: 'futbol',
    rareza: 'raro',
    titulo: 'El gol del año',
    texto:
      'La agarraste de treinta metros y entró en el ángulo. El estadio hizo un ruido que no habías escuchado nunca.',
    tipoDeRecuerdo: 'gol',
    condiciones: { temporadasMin: 1 },
    cooldown: 4,
    opciones: [
      {
        id: 'dedicar',
        texto: 'Dedicárselo a la hinchada',
        efectos: {
          vida: { carinoDeLaHinchada: 12, fama: 8 },
          relaciones: { hinchada: { confianza: 10 } },
          titular: { texto: 'EL GOLAZO DE {APELLIDO} QUE DIO LA VUELTA AL MUNDO', tono: 'elogio' },
          balance: 5,
        },
        resultado: 'Corriste hasta la popular y te la dedicaste a ellos. El video superó los diez millones.',
      },
      {
        id: 'festejo-frio',
        texto: 'Festejarlo serio, señalando al que asistió',
        efectos: {
          relaciones: { companeros: { confianza: 8 } },
          vida: { reputacion: 5 },
          balance: 4,
        },
        resultado: 'Ni una mueca: levantaste el brazo señalando a quien te la dio y volviste al medio.',
      },
      {
        id: 'dedicarlo',
        texto: 'Dedicárselo a alguien de tu vida',
        pista: 'La cámara lo va a agarrar todo.',
        efectos: {
          vida: { carinoDeLaHinchada: 14, felicidad: 14, exposicion: 8 },
          personalidad: { carisma: 5 },
          etiquetas: ['vida:familia'],
          balance: 5,
        },
        resultado: 'Levantaste la camiseta con un nombre escrito abajo. Fue la foto del año.',
      },
      {
        id: 'nada',
        texto: 'Festejarlo como si fuera uno más',
        pista: 'Serio. Profesional. Frío.',
        efectos: {
          personalidad: { profesionalismo: 6, ego: -4 },
          relaciones: { dt: { respeto: 8 } },
          balance: 2,
        },
        resultado: 'Lo festejaste señalando al que te la pasó y volviste al círculo caminando.',
      },
    ],
  },
  {
    id: 'futbol-final',
    categoria: 'futbol',
    rareza: 'epico',
    titulo: 'La final',
    texto: 'Llegaron a la final. Noventa minutos entre una vida de trabajo y una vitrina vacía.',
    tipoDeRecuerdo: 'decision',
    condiciones: { temporadasMin: 1, clubFuerzaMin: 62 },
    cooldown: 4,
    opciones: [
      {
        id: 'concentrado',
        texto: 'Encerrarte a preparar el partido',
        efectos: {
          vida: { estres: 8, forma: 6 },
          personalidad: { profesionalismo: 3 },
          balance: 5,
        },
        resultado: 'Apagaste el teléfono cuatro días. Llegaste al partido como si fuera un entrenamiento más.',
      },
      {
        id: 'disfrutar',
        texto: 'Disfrutar la semana con tu gente',
        efectos: {
          vida: { felicidad: 10, estres: -6, forma: -3 },
          relaciones: { pareja: { confianza: 6 } },
          balance: 3,
        },
        resultado: 'Pasaste la semana con los tuyos. Salías a la cancha con una calma rara.',
      },
      {
        id: 'hablar-antes',
        texto: 'Hablarle al plantel antes de salir',
        pista: 'Si sale bien, es tu equipo desde hoy.',
        efectos: {
          personalidad: { carisma: 8 },
          relaciones: { companeros: { respeto: 14, confianza: 10 } },
          etiquetas: ['social:lider'],
          balance: 5,
        },
        resultado: 'Hablaste dos minutos en el vestuario. No se escuchó ni una respiración.',
      },
      {
        id: 'rutina',
        texto: 'Hacer exactamente lo mismo de siempre',
        pista: 'Una final es un partido. Convencete.',
        efectos: {
          vida: { estres: -12, confianza: 6 },
          personalidad: { profesionalismo: 7 },
          balance: 4,
        },
        resultado: 'La misma música, la misma comida, la misma siesta. Saliste a la cancha como un martes.',
      },
    ],
  },
];
